[project]
name = "MangaReader"
version = "0.1.0"
description = "本子浏览器"
readme = "README.md"
requires-python = ">=3.11,<3.14"
authors = [
  { name = "kawayiYokami" }
]
license = { file = "LICENSE" }
keywords = ["manga", "reader", "comic", "image-processing"]
classifiers = [
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Topic :: Multimedia :: Graphics :: Viewers"
]

dependencies = [
    "pywebview==5.4",
    "pyyaml==6.0.1",
    "openai",
    "requests",
    "uvicorn",
    "fastapi",
    "Pillow",
    "opencv-contrib-python",
    "filelock",
    "coloredlogs",
    "python-multipart",
    "fonttools",
    "uvicorn[standard]",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = [
    "core",
    "web",
    "web.api",
    "web.websocket",
    "web.utils",
    "utils"
]

[tool.uv.workspace]
members = [
    "Image_Translator_LMM_GUI",
]
